### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dosbubba** [ahegazy/php-mvc-skeleton#3]
If you have a website where the header (**/app/views/layout/header.php**) is different for logged in users and not logged in users, how would you implement that?

The difference is one header for anonymous users that contains a Sign In button and a drop down menu of other account options and one that contains Log Out button instead for logged in users.

I can think of 2 possible solutions:

> 1. Pass the data to the view through the $data[] associative array. (ex: $data['loggedin] = 0 or 1 for true and false). Then add the logic (an if statement) within **/app/views/layout/header.php** to render the right content. _Is it appropriate to put if statement logic within a view?_
> 
> 2. Have the Model call a different view if user is logged in (for example: **/app/views/layout/header.php** and **/app/views/layout/user_header.php**).

Any thoughts would be greatly appreciated.

**Comment by ahegazy** [comment]
Hey, 
It's been a while since i last checked the project, but i took a quick look and I think the second solution would be better for modularity .

You already have `$loggedUser` variable in `/app/core/Controller.php` so you can just modify the [view](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L59) function to include different header in case the user is logged in.

**Comment by dosbubba** [comment]
Thank you. This project has helped me a lot with learning PHP MVC.

**Comment by ahegazy** [comment]
Happy to hear that, you are welcome.
