### ISSUE TITLE
Can I merge two unmodified original MVCs into one MVC?

### ISSUE THREAD

**Issue by gusbemacbe** [ahegazy/php-mvc-skeleton#4]
Hello @ahegazy!

Look at @lucas-ayabe's https://github.com/Lucas-Ayabe/simple-mvc skeleton. If I keep Lucas' original MVC skeleton, can I merge your original MVC skeleton into his MVC skeleton? I want to build a multilingual site. But not only it, your repo also has login, so it is another advantage. I want to keep his original code because of PHPMailer. Lucas' router page uses Composer. 

Thank you for your attention and your understanding!

**Comment by ahegazy** [comment]
Hi @gusbemacbe,
IMO the best course of action for you is to read my implementation [README](https://github.com/ahegazy/php-mvc-skeleton/blob/master/README.md), understand each part of the design, and understand the other repo's code, then integrate them together, by taking what you need from my repo.

For example, you need the multilingual feature, in my design the url looks like `URL/language/controller/method/parameters`
the [APP](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/App.php) reads the request, extracts the language, then [checks](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/App.php#L25) if the language file exists in the languages directory and defines a `LANGUAGE` global variable, and in the [view](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L37) function in the controller main class it includes the language variables to the [$data](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L55) array which is readable in the [requested view file](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L59).

I'venot touched this project in a while, so my memory is fuzzy design wise, but the documentation and the comments are sufficient to fully understand how it works and integrate it with anything else, otherwise, you can clone the project and add composer and PHPMailer  to the design as is.

**Comment by ahegazy** [comment]
Hi @gusbemacbe,
IMO the best course of action for you is to read my implementation [README](https://github.com/ahegazy/php-mvc-skeleton/blob/master/README.md), understand each part of the design, and understand the other repo's code, then integrate them together, by taking what you need from my repo.

For example, you need the multilingual feature, in my design the url looks like `URL/language/controller/method/parameters`
the [APP](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/App.php) reads the request, extracts the language, then [checks](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/App.php#L25) if the language file exists in the languages directory and defines a `LANGUAGE` global variable, and in the [view](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L37) function in the controller main class it includes the language variables to the [$data](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L55) array which is readable in the [requested view file](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php#L59).

I'venot touched this project in a while, so my memory is fuzzy design wise, but the documentation and the comments are sufficient to fully understand how it works and integrate it with anything else, otherwise, you can clone the project and add composer and PHPMailer  to the design.
